# This is a basic workflow to help you get started with Actions

name: Convert md to html
on: [push, workflow_dispatch]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Export HTML
        run: npm exec @marp-team/marp-cli@latest Notes.md -o PyTexasSlides.html

      - name: Export PDF
        run: npm exec @marp-team/marp-cli@latest Notes.md -o PyTexasSlides.pdf
      
      - name: Archive Exports
        uses: actions/upload-artifact@v2
        with:
          name: Notes Exports
          path: PyTexasSlides.*
          retention-days: 7
      
      - name: Tag branch
        if: endswith(github.ref, 'main')
        uses: mydea/action-tag-date-version@v20

      - name: Release HTML
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          artifacts: PyTexasSlides.*
          token: ${{ secrets.GITHUB_TOKEN }}
